### PR TITLE
Added support for DHCP resolution to WpadProxySearchStrategy

### PR DESCRIPTION
**Pull request by RocusHalbasch**
Made a couple minor changes to the DHCPSocket and DHCPOptions classes to
make them able to handle Option 252 and capable of sending on a specific
interface. Then used them to send DHCPInform messages on all interfaces
with valid IPv4 addresses and check the responses for Option 252. Also
added WPAD to the Strategy enum so it can be tested with ProxyTester and
added as a Strategy.

### CODE REVIEW

**Comment by RocusHalbasch** [comment]
This seems more significant now that Firefox even supports DHCP resolution, as do KDE, and OSX.

**Comment by MarkusBernhardt** [comment]
Hi Rocus,

 

many, many thanks for your input. Will try to get a look on the code by the end of the week, integrate some more things and push out a new release by the weekend.

 

Best regards,

Markus

 

Von: Rocus Halbasch <notifications@github.com> 
Gesendet: Mittwoch, 26. September 2018 20:01
An: MarkusBernhardt/proxy-vole <proxy-vole@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [MarkusBernhardt/proxy-vole] Added support for DHCP resolution to WpadProxySearchStrategy (#53)

 

This seems more significant now that Firefox even supports DHCP resolution, as do KDE, and OSX.

**Comment by MarkusBernhardt** [comment]
Wow. That looks really awesome. A little hard to test for me, but as it does not break my test cases I will merge it now.

**Comment by RocusHalbasch** [comment]
There is a possibility I missed a case or two with some dhcp servers. If you get any issues with the implementation please feel free to contact me and I'll take a stab at them.

**Pull request merged**
